FROM Node:apline-20

WORKDIR /usr/arc/app

COPY ./packages ./packages
COPY pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./apps/website ./apps/website

RUN pnpm install
RUN pnpm build

EXPOSE 3001

CMD [ "pnpm", "run","start:website" ]