FROM node:20-alpine

WORKDIR /usr/arc/app

COPY ./packages ./packages
COPY pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./apps/website ./apps/website

RUN npm i -g pnpm
RUN pnpm install
RUN pnpm build

EXPOSE 3001

CMD [ "pnpm", "run","start:website" ]