name: Deploy To Tweetly Website
on:
  push:
      branches: [main]

jobs:
    redeploy_everything:
                        runs-on: ubuntu-latest
                        name: Deploy Everything
                        steps:
                          - name: Checkout the code
                            uses: actions/checkout@v2


                        
                          - name: executing remote ssh commands using ssh key
                            uses: appleboy/ssh-action@v1.2.0
                            with:
                              host: 34.131.110.188
                              username: avishmadaan
                              key: ${{secrets.SSH_PRIVATE_KEY}}
                              port: 22
                              script: |
                                  export PATH=/home/avishmadaan/.nvm/versions/node/v22.14.0/bin:$PATH
                                  cd tweetly
                                  git stash push -m "local"
                                  git pull 
                                  npm i -g pnpm
                                  pnpm install
                                  echo "everything set here"
                                  pnpm run build
                                  pm2 restart http-server
    